version: '3.9'

services:
  frontend:
    image: php:7.4-apache
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html/frontend
    depends_on:
      - goapp

  goapp:
    image: golang:1.17
    container_name: goapp
    restart: always
    working_dir: /app
    volumes:
      - ./goapp:/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: akcommodities
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
